# MongoDB for local development
spring.data.mongodb.uri=mongodb://localhost:27017/kavyaprodb_dev
spring.data.mongodb.auto-index-creation=true

# Run server on different port when using dev if desired
server.port=8080

